# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    cron: "puppet/cron"
    docker: "puppetlabs/docker"
    inifile: "puppetlabs/inifile"
    nginx: "puppet/nginx"
    nfs: "derdanne/nfs"
    puppetdb: "puppetlabs/puppetdb"
    firewall: "puppetlabs/firewall"
    apt: "puppetlabs/apt"
    yumrepo_core: "puppetlabs/yumrepo_core"
    archive: "puppet/archive"
    translate: "puppetlabs/translate"
    accounts: "puppetlabs/accounts"
    sudo: "saz/sudo"
    motd: "puppetlabs/motd"
    puppetboard: "puppet/puppetboard"
    python: "puppet/python"
    concat: "puppetlabs/concat"
    epel: "puppet/epel"
    postgresql: "puppetlabs/postgresql"
    cron_core: "puppetlabs/cron_core"
    sshkeys_core: "puppetlabs/sshkeys_core"
    mount_core: "puppetlabs/mount_core"
